### ISSUE TITLE
Doesn't work with jsdom >= 10.0.0

### ISSUE THREAD

**Issue by atd** [jmeas/simple-jsdom#14]
jsdom changed the API in version 10.0.0

https://github.com/tmpvar/jsdom/blob/master/Changelog.md#1000

Newer versions show the following error:

```
Message:                  
    jsdom is not a function                          
Stack:                    
TypeError: jsdom is not a function                   
    at Object.<anonymous> (/home/atd/dev/cartodb.js/node_modules/simple-jsdom/index.js:4:16)              
    at Module._compile (module.js:570:32)            
```

**Comment by jamesplease** [comment]
Thanks @atd , I'll take a look. Also, it's worth noting that [this lib](https://github.com/rstacruz/jsdom-global) seems to work with jsdom 10.0.0 and had better marketing than this lib, so everyone is usin' that these days! :)

**Comment by atd** [comment]
Thank you for the pointer @jmeas ! Very considerate from you.

I ended up switching libraries because of another issue: it seems to be a race condition and tests are passed before the global namespace is modified
